In [6]:
import numpy as np

In [8]:
vetor = [1, 5, 9]

In [10]:
type(vetor)

list

In [12]:
meuvetor = np.array(vetor)

In [7]:
meuvetor

array([1, 5, 9])

In [14]:
type(meuvetor)

numpy.ndarray

In [16]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
np.zeros(shape=(4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
type(0)

int

In [24]:
type(0.)

float