In [1]:
import numpy as np

In [17]:
#Criar duas matrizes!
matrizA = np.array([[2,3],[1,4]])
matrizB = np.array([[7,8],[5,6]])

In [18]:
matrizA

array([[2, 3],
       [1, 4]])

In [19]:
matrizB

array([[7, 8],
       [5, 6]])

In [20]:
somarAB = matrizA + matrizB

In [21]:
somarAB

array([[ 9, 11],
       [ 6, 10]])

In [22]:
print(somarAB)

[[ 9 11]
 [ 6 10]]


In [23]:
somarAB.shape

(2, 2)

In [24]:
#Outra forma de efetuar a soma de matrizes é usando o numpy
somarAB2 = np.add(matrizA, matrizB)

In [25]:
somarAB2

array([[ 9, 11],
       [ 6, 10]])