In [4]:
import numpy as np

In [11]:
# Forma de lista
vetor = [1, 5, 9, 10, 6]

In [13]:
type(vetor)

list

In [14]:
vetor

[1, 5, 9, 10, 6]

In [15]:
# Forma de array usando numpy
#Mais eficiente, usa menos memória
#Mais preparado para executar operações numéricas.
meuvetor = np.array(vetor)

In [17]:
type(meuvetor)

numpy.ndarray

In [18]:
meuvetor

array([ 1,  5,  9, 10,  6])

In [23]:
v = np.arange(1,100,2)

In [24]:
v

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [28]:
np.zeros(shape=(8,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
np.ones(shape=(6,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
type(0)

int

In [15]:
type(0.)

float