In [2]:
import numpy as np

In [3]:
np.random.seed(101)
vetor = np.random.randint(0,100,10)

In [4]:
vetor.shape

(10,)

In [5]:
vetor

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40], dtype=int32)

In [9]:
vetor.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]], dtype=int32)

In [10]:
vetor.reshape((5,2))

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]], dtype=int32)

In [11]:
vetor.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]], dtype=int32)

In [12]:
vetor.mean()

np.float64(60.8)

In [13]:
vetor.max()

np.int32(95)

In [14]:
vetor.argmax()

np.int64(0)

In [32]:
vetor2 = np.random.randint(0,200,9)

In [33]:
vetor2

array([180, 184, 103,  38,  73, 180, 146,  71, 103], dtype=int32)

In [34]:
vetor2.shape

(9,)

In [47]:
vetor2 = vetor2.reshape(3,3)

In [48]:
vetor2.shape

(3, 3)

In [49]:
vetor2

array([[180, 184, 103],
       [ 38,  73, 180],
       [146,  71, 103]], dtype=int32)