In [2]:
import numpy as np

In [3]:
np.random.seed(101)
vetor = np.random.randint(0,100,10)

In [6]:
vetor.shape

(10,)

In [8]:
vetor

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [10]:
vetor.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [12]:
vetor.reshape((5,2))

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])