In [1]:
import numpy as np
from numpy import genfromtxt

In [3]:
dados = genfromtxt('dados/bank_note_data.txt',delimiter=',')

In [4]:
dados

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
classes = dados[:,4]

In [8]:
classes

array([0., 0., 0., ..., 1., 1., 1.])

In [11]:
registros = dados[:,0:4]

In [13]:
registros

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [15]:
X = registros
y = classes

In [17]:
#Dividir a base de dados em treinamento e teste
#divide e mistura os registros para distribuir
from sklearn.model_selection import train_test_split


In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [19]:
len(X_train)

919

In [23]:
len(X)

1372

In [25]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [27]:
y_train

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 0.

In [29]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 0.

In [31]:
#Normalizar os dados entre zero e um
from sklearn.preprocessing import MinMaxScaler

In [33]:
X_test.min()

np.float64(-13.2869)

In [35]:
X_test.max()

np.float64(17.1116)

In [37]:
scaler_object = MinMaxScaler()

In [39]:
#Usa apenas a base de dados de treino para normalizar. Sendo justo.
scaler_object.fit(X_train)
#scaler_object.fit(X)

MinMaxScaler()

In [41]:
scaled_X_train = scaler_object.transform(X_train)

In [43]:
scaled_X_teste = scaler_object.transform(X_test)

In [45]:
scaled_X_train.max()

np.float64(1.0000000000000002)

In [47]:
scaled_X_train.min()

np.float64(0.0)

In [49]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\Fabricio\anaconda3\envs\meu_env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Fabricio\anaconda3\envs\meu_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Fabricio\anaconda3\envs\meu_env\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\Fabricio\anaconda3\envs\meu_env\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instan

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\Fabricio\anaconda3\envs\meu_env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Fabricio\anaconda3\envs\meu_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Fabricio\anaconda3\envs\meu_env\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\Fabricio\anaconda3\envs\meu_env\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instan

AttributeError: _ARRAY_API not found

ImportError: numpy.core._multiarray_umath failed to import

ImportError: numpy.core.umath failed to import

TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle

In [26]:
model = Sequential()

model.add(Dense(4,input_dim=4, activation='relu'))
          
model.add(Dense(8,activation='relu'))
          
model.add(Dense(1,activation='sigmoid'))

          

In [27]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics = ['accuracy'])

In [28]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
29/29 - 2s - loss: 0.6594 - accuracy: 0.6148 - 2s/epoch - 68ms/step
Epoch 2/50
29/29 - 0s - loss: 0.6497 - accuracy: 0.6268 - 138ms/epoch - 5ms/step
Epoch 3/50
29/29 - 0s - loss: 0.6408 - accuracy: 0.6376 - 155ms/epoch - 5ms/step
Epoch 4/50
29/29 - 0s - loss: 0.6312 - accuracy: 0.6670 - 94ms/epoch - 3ms/step
Epoch 5/50
29/29 - 0s - loss: 0.6198 - accuracy: 0.6823 - 58ms/epoch - 2ms/step
Epoch 6/50
29/29 - 0s - loss: 0.6062 - accuracy: 0.6768 - 61ms/epoch - 2ms/step
Epoch 7/50
29/29 - 0s - loss: 0.5908 - accuracy: 0.7008 - 68ms/epoch - 2ms/step
Epoch 8/50
29/29 - 0s - loss: 0.5738 - accuracy: 0.7127 - 53ms/epoch - 2ms/step
Epoch 9/50
29/29 - 0s - loss: 0.5554 - accuracy: 0.7247 - 60ms/epoch - 2ms/step
Epoch 10/50
29/29 - 0s - loss: 0.5361 - accuracy: 0.7410 - 63ms/epoch - 2ms/step
Epoch 11/50
29/29 - 0s - loss: 0.5178 - accuracy: 0.7388 - 60ms/epoch - 2ms/step
Epoch 12/50
29/29 - 0s - loss: 0.4992 - accuracy: 0.7650 - 66ms/epoch - 2ms/step
Epoch 13/50
29/29 - 0s - loss: 0.480

In [39]:

predicao = (model.predict(scaled_X_teste) > 0.5).astype("int32").flatten() # Para classe binária model.predict(scaled_X_teste)
predicoes = model.predict(scaled_X_teste)
#classes_preditas = np.argmax(predicoes, axis = 1)
#display(classes_preditas)


15/15 [==============================] - 0s 2ms/step


In [40]:
from sklearn.metrics import confusion_matrix, classification_report

In [41]:
model.metrics_names

['loss', 'accuracy']

In [42]:

classes_preditas = (predicoes > 0.5).astype("int32").flatten()

# Avaliação do modelo
print("\nMatriz de Confusão:")
print(confusion_matrix(y_test, classes_preditas))

print("\nRelatório de Classificação:")
print(classification_report(y_test, classes_preditas))


Matriz de Confusão:
[[254   3]
 [  4 192]]

Relatório de Classificação:
              precision    recall  f1-score   support

         0.0       0.98      0.99      0.99       257
         1.0       0.98      0.98      0.98       196

    accuracy                           0.98       453
   macro avg       0.98      0.98      0.98       453
weighted avg       0.98      0.98      0.98       453



In [43]:
print("Classes previstas:", classes_preditas[:50])  # Mostra as 10 primeiras previsões


Classes previstas: [0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 1 0 1
 1 1 0 0 1 1 0 1 1 1 0 0 1]


In [44]:
model.save('meumodel.h5')

In [45]:
from keras.models import load_model

In [46]:
novoModel = load_model('meumodel.h5')

In [47]:
predicoes2 = novoModel.predict(scaled_X_teste)

classes_preditas = (predicoes2 > 0.5).astype("int32").flatten()

# Avaliação do modelo
print("\nMatriz de Confusão:")
print(confusion_matrix(y_test, classes_preditas))

print("\nRelatório de Classificação:")
print(classification_report(y_test, classes_preditas))

classes_preditas

15/15 [==============================] - 0s 7ms/step

Matriz de Confusão:
[[254   3]
 [  4 192]]

Relatório de Classificação:
              precision    recall  f1-score   support

         0.0       0.98      0.99      0.99       257
         1.0       0.98      0.98      0.98       196

    accuracy                           0.98       453
   macro avg       0.98      0.98      0.98       453
weighted avg       0.98      0.98      0.98       453



array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,